apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: skopos-kibana
  namespace: skopos
spec:
  version: 8.13.0
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: skopos-es
  config:
    elasticsearch.hosts: ["http://skopos-es-es-http.skopos.svc:9200"]
    xpack.encryptedSavedObjects.encryptionKey: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
